table PeriodsSelection
	lineageTag: b94b1668-75e3-470a-be77-032469532201

	column Period
		dataType: string
		lineageTag: e1f156e9-a10c-4e68-bb18-8730dfe7140d
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column 'Period Sort'
		dataType: int64
		formatString: 0
		lineageTag: 834df874-2090-4ae8-86f7-60068adae048
		summarizeBy: sum
		sourceColumn: Period Sort

		annotation SummarizationSetBy = Automatic

	partition PeriodsSelection = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci4tKkrNK1Hwzc8ryVDSUTJUitVBiEamJhYBBY2ggsUl+blArrFSbCwA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t, #"Period Sort" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Period", type text}, {"Period Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

